Added model schema and migrations
IshmeetSingh06/rails-event-management pull request #1
Opened 2023-08-21 08:37 UTC by IshmeetSingh06

2023-08-21 09:51 UTC, gagan93jtg requested changes, later dismissed

2023-08-21 09:51 UTC, gagan93jtg commented on config/database.yml
> +  port: 5000
why the specific port?

2023-08-21 09:51 UTC, gagan93jtg commented on test/models/user_test.rb
> +require "test_helper"
remove fixtures and test files. We prefer Rspec with factories. Both of which will be added later. For now, skip committing test files

2023-08-22 07:18 UTC, PramanSatya requested changes

2023-08-22 07:18 UTC, PramanSatya commented on db/migrate/20230821082821_create_events.rb
> +      t.datetime :date_time
event_time

2023-08-22 07:18 UTC, PramanSatya commented on db/migrate/20230821082856_create_registrations.rb
> +      t.references :user, null: false, foreign_key: true
AFAIK we don't need ```null: false``` here
Please check there is already a validation in rails to check null for associations unless ```optional: true``` is given

2023-08-22 07:18 UTC, PramanSatya commented on app/models/user.rb
> +class User < ApplicationRecord
user can have many registrations, right?
Also, admin user can have many events

2023-08-24 08:26 UTC, PramanSatya approved these changes

2023-08-24 08:57 UTC, merged