Feat user controller
IshmeetSingh06/rails-event-management pull request #3
Opened 2023-08-22 11:05 UTC by IshmeetSingh06

2023-08-24 09:10 UTC, PramanSatya requested changes

2023-08-24 09:10 UTC, PramanSatya commented on app/controllers/application_controller.rb
> +      user = User.find_by!(authentication_token: token)
I don't think there is a need for begin rescue here.
Check if user is present else show unauthorized

2023-08-24 09:10 UTC, PramanSatya commented on app/controllers/application_controller.rb
> +        self.current_user ||= user
any reason to use memoisation here?

2023-08-24 09:10 UTC, PramanSatya commented on app/models/user.rb
> +  # def errors
remove unnecessary code

2023-08-24 09:10 UTC, PramanSatya commented on app/models/user.rb
> +  def serializable_hash(options = nil)
usecase?

2023-08-24 09:10 UTC, PramanSatya commented on app/services/users_service.rb
> +      user = User.create!(params)
You are not doing some custom stuff inside particular rescues, same thing is happening in all. This can be helpful if in case we have to trigger different mailers at different stages of failures. Makes sense?
Can do something simple like:
```ruby
user = User.new(params)
if user.save
  self.authentication_token = user.authentication_token
else
  self.errors = user.errors.full_messages
end
```

2023-08-24 09:10 UTC, PramanSatya commented on app/services/users_service.rb
> +      current_user.attended_events
There should be 2 APIs,
1. See list of all attended events(list_all_events -> attended_events)
2. See list of all upcoming events with all details

2023-08-24 09:10 UTC, PramanSatya commented on app/services/users_service.rb
> +  def register_event(event_id)
register_event_attendee

2023-08-24 09:10 UTC, PramanSatya commented on app/controllers/api/v1/users_controller.rb
> +  def register
look for better name, register inside users_controller should ideally register users only

2023-08-24 09:10 UTC, PramanSatya commented on app/services/users_service.rb
> +      event_from_id = Event.find(event_id)
event_from_id -> event

2023-08-24 09:52 UTC, gagan93jtg commented on app/controllers/api/v1/users_controller.rb
> +  before_action :require_admin, only: [:deactivate, :list_all]
no action found with name `list_all`

2023-08-24 09:52 UTC, gagan93jtg commented on app/controllers/api/v1/users_controller.rb
> +  def list_events
`events`

2023-08-24 09:52 UTC, gagan93jtg commented on app/controllers/api/v1/users_controller.rb
> +    result = UsersService.new
`service = UsersService.new`. 
Don't take variable name as `result` because no result is retrieved in line 28. Same for other usages.

2023-08-24 09:52 UTC, gagan93jtg commented on app/controllers/application_controller.rb
> +    rescue ActiveRecord::RecordNotFound=> error
space before `=>` incase you need exception handling

2023-08-24 09:52 UTC, gagan93jtg commented on db/seeds.rb
>  #   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
remove sample data

2023-08-24 10:05 UTC, IshmeetSingh06 commented on app/models/user.rb
> +  def serializable_hash(options = nil)
there is one index route for users , which would list all of them , there i dont want to return authentication field

2023-08-24 11:34 UTC, neeraj33negi commented on app/controllers/application_controller.rb
> +      user = User.find_by!(authentication_token: token)
create a scope for active and use `User.active.find_by!(authentication_token: token)`

2023-08-25 09:03 UTC, PramanSatya commented on app/models/user.rb
> +  def serializable_hash(options = nil)
The API is exposed to admins only, we can show auth_tokens to admin users, right?

2023-08-25 09:04 UTC, PramanSatya commented on app/controllers/api/v1/users_controller.rb
> +  def create
Not able to see API for list of upcoming events for guest

2023-08-29 02:50 UTC, neeraj33negi requested changes

2023-08-29 02:50 UTC, neeraj33negi commented on app/services/guest_service.rb
> +    end
```suggestion
    user = User.new(params)
    if user.save
      self.authentication_token = user.authentication_token
    else
      self.errors = user.errors.full_messages
    end
```

2023-08-29 02:50 UTC, neeraj33negi commented on app/services/guest_service.rb
> +    end
this would prevent a case when params contain `created_at`

2023-08-29 02:50 UTC, neeraj33negi commented on app/services/guest_service.rb
> +      Registration.create(user_id: current_user.id, event_id: event_id)
what if this create return false?

2023-08-29 02:50 UTC, neeraj33negi commented on app/services/users_service.rb
> +      self.errors = user.errors.full_messages unless user.update!(active: false)
`update!` raises Exception on failure rather than returning a bool

2023-08-29 02:52 UTC, neeraj33negi commented on app/controllers/api/v1/users_controller.rb
> +    end
in both case, there should be same response format.

2023-08-29 02:52 UTC, neeraj33negi commented on app/controllers/api/v1/users_controller.rb
> +    end
here too

2023-08-31 08:52 UTC, PramanSatya approved these changes

2023-08-31 09:51 UTC, merged